version: "3.9"

services:

  kerberos-server:
    hostname: kerberos-server
    build: images/kerberos/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - ./configs/kerberos/kdc.conf:/etc/krb5kdc/kdc.conf
      - ./configs/kerberos/kadm5.acl:/etc/krb5kdc/kadm5.acl
    networks:
      hadoop:
        ipv4_address: 192.168.100.200
    environment:
      KRB5_TRACE: /dev/stdout
      KRB5_CONFIG: /etc/krb5/krb5.conf
      KRB5_KDC_PROFILE: /etc/krb5kdc/kdc.conf
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        # Creating KDC Database
        echo -e "dumbmasterpasswd\ndumbmasterpasswd\n" | kdb5_util create -s
        # Creating kadmin User
        kadmin.local -q "addprinc -pw dumbadminpasswd admin/admin@HADOOP.LOCAL"
        # Starting kadmin daemon
        kadmind
        # Starting KDC server (not in daemon mode)
        krb5kdc -n
    expose:
      - 88
      - 464
      - 749

  namenode-1:
    hostname: namenode-1
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - type: tmpfs
        target: /usr/local/hadoop/hadoop_data/namenode
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.2
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        sudo chown -R 1000:1000 /usr/local/hadoop # change ownership for hdfs (fs mounted with root ownership)
        hdfs namenode -format
        hdfs namenode
    expose:
      - 9870

  datanode-1:
    hostname: datanode-1
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - type: tmpfs
        target: /usr/local/hadoop/hadoop_data/datanode
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.3
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        sudo chown -R 1000:1000 /usr/local/hadoop # change ownership for hdfs (fs mounted with root ownership)
        hdfs datanode
    depends_on:
      - namenode-1
    expose:
      - 9864

  datanode-2:
    hostname: datanode-2
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - type: tmpfs
        target: /usr/local/hadoop/hadoop_data/datanode
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.4
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        sudo chown -R 1000:1000 /usr/local/hadoop # change ownership for hdfs (fs mounted with root ownership)
        hdfs datanode
    depends_on:
      - namenode-1
    expose:
      - 9864

  datanode-3:
    hostname: datanode-3
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - type: tmpfs
        target: /usr/local/hadoop/hadoop_data/datanode
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.5
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        sudo chown -R 1000:1000 /usr/local/hadoop # change ownership for hdfs (fs mounted with root ownership)
        hdfs datanode
    depends_on:
      - namenode-1
    expose:
      - 9864

  resourcemanager-1:
    hostname: resourcemanager-1
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/capacity-scheduler.xml:/etc/hadoop/conf/capacity-scheduler.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - type: tmpfs
        target: /home/hadoop
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.51
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
      HADOOP_HOME: /opt/hadoop
      HADOOP_MAPRED_HOME: /opt/hadoop
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        yarn resourcemanager
    expose:
      - 8088

  nodemanager-1:
    hostname: nodemanager-1
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/capacity-scheduler.xml:/etc/hadoop/conf/capacity-scheduler.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - type: tmpfs
        target: /home/hadoop
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.52
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
      HADOOP_HOME: /opt/hadoop
      HADOOP_MAPRED_HOME: /opt/hadoop
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        yarn nodemanager
    depends_on:
      - resourcemanager-1
    expose:
      - 8042

  nodemanager-2:
    hostname: nodemanager-2
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/capacity-scheduler.xml:/etc/hadoop/conf/capacity-scheduler.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - type: tmpfs
        target: /home/hadoop
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.53
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
      HADOOP_HOME: /opt/hadoop
      HADOOP_MAPRED_HOME: /opt/hadoop
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        yarn nodemanager
    depends_on:
      - resourcemanager-1
    expose:
      - 8042

  edge-1:
    hostname: edgenode-1
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - ./configs/kerberos/krb5.conf:/var/kerberos/krb5kdc/krb5.conf
      - type: tmpfs
        target: /home/hadoop
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.100
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
      HADOOP_HOME: /opt/hadoop
      HADOOP_MAPRED_HOME: /opt/hadoop
      KRB5_CONFIG: /var/kerberos/krb5kdc/krb5.conf
    command:
      - /bin/bash
      - --verbose
      - -c

      - |
        sudo chown -R 1000:1000 /usr/local/hadoop # change ownership for hdfs (fs mounted with root ownership)
        sudo chown -R 1000:1000 /home/hadoop      # change ownership for hdfs (fs mounted with root ownership)
        tail -f /dev/null
    depends_on:
      - namenode-1
      - resourcemanager-1

networks:
  hadoop:
    ipam:
      config:
        - subnet: 192.168.100.0/24
