version: "3.9"

services:

  kerberos-server:
    hostname: kerberos-server
    build: images/kerberos/.
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - ./configs/kerberos/kdc.conf:/etc/krb5kdc/kdc.conf
      - ./configs/kerberos/kadm5.acl:/etc/krb5kdc/kadm5.acl
    networks:
      hadoop:
        ipv4_address: 192.168.100.200
    env_file:
      - ./env-files/kerberos.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        # Creating KDC Database
        echo -e "dumbmasterpasswd\ndumbmasterpasswd\n" | kdb5_util create -s
        # Creating kadmin User
        kadmin.local -q "addprinc -pw dumbadminpasswd admin/admin@HADOOP.LOCAL"
        # Starting kadmin daemon
        kadmind
        # Starting KDC server (not in daemon mode)
        krb5kdc -n
    expose:
      - 88
      - 464
      - 749

  namenode-1:
    hostname: namenode-1
    build: images/hadoop/.
    user: hdfs
    tty: false
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.2
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
         hdfs namenode -format
         hdfs namenode
    expose:
      - 9870

  datanode-1:
    hostname: datanode-1
    build: images/hadoop/.
    user: hdfs
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.3
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        hdfs datanode
    depends_on:
      - namenode-1
    expose:
      - 9864

  datanode-2:
    hostname: datanode-2
    build: images/hadoop/.
    user: hdfs
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.4
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        hdfs datanode
    depends_on:
      - namenode-1
    expose:
      - 9864

  datanode-3:
    hostname: datanode-3
    build: images/hadoop/.
    user: hdfs
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.5
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        hdfs datanode
    depends_on:
      - namenode-1
    expose:
      - 9864

  resourcemanager-1:
    hostname: resourcemanager-1
    build: images/hadoop/.
    user: yarn
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/capacity-scheduler.xml:/etc/hadoop/conf/capacity-scheduler.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.51
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        yarn resourcemanager
    expose:
      - 8088

  nodemanager-1:
    hostname: nodemanager-1
    build: images/hadoop/.
    user: yarn
    cpus: 1
    mem_limit: 1G
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/capacity-scheduler.xml:/etc/hadoop/conf/capacity-scheduler.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.52
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        yarn nodemanager
    depends_on:
      - resourcemanager-1
    expose:
      - 8042

  nodemanager-2:
    hostname: nodemanager-2
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    user: yarn
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/capacity-scheduler.xml:/etc/hadoop/conf/capacity-scheduler.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.53
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        yarn nodemanager
    depends_on:
      - resourcemanager-1
    expose:
      - 8042

  edge-1:
    hostname: edgenode-1
    build: images/hadoop/.
    cpus: 1
    mem_limit: 1G
    user: hadoop
    volumes:
      - ./configs/hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./configs/hadoop/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./configs/hadoop/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./configs/hadoop/mapred-site.xml:/etc/hadoop/conf/mapred-site.xml
      - ./configs/kerberos/krb5.conf:/etc/krb5/krb5.conf
      - type: tmpfs
        target: /opt/hadoop/hadoop_data
        tmpfs:
          size: 10000000000 # 10 GB
    networks:
      hadoop:
        ipv4_address: 192.168.100.100
    env_file:
      - ./env-files/hadoop.env
    command:
      - /bin/bash
      - --verbose
      - -c
      - |
        tail -f /dev/null
    depends_on:
      - namenode-1
      - resourcemanager-1

networks:
  hadoop:
    ipam:
      config:
        - subnet: 192.168.100.0/24
